// <auto-generated />
using BitirmeProjesiErp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeProjesiErp.Migrations.Fiyatlar
{
    [DbContext(typeof(FiyatlarContext))]
    partial class FiyatlarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BitirmeProjesiErp.Models.Fiyat1", b =>
                {
                    b.Property<string>("_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("fiyat1");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Fiyat2", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("fiyat2");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Fiyat3", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("fiyat3");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Fiyat4", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("fiyat4");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Fiyat5", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("fiyat5");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Fiyat6", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("fiyat6");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Yedek1", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("yedek1");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Yedek2", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("yedek2");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Yedek3", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("yedek3");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Yedek4", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("genislik")
                        .HasColumnType("int");

                    b.Property<int>("uzunluk")
                        .HasColumnType("int");

                    b.HasKey("_key");

                    b.ToTable("yedek4");
                });
#pragma warning restore 612, 618
        }
    }
}
