// <auto-generated />
using BitirmeProjesiErp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeProjesiErp.Migrations.scf
{
    [DbContext(typeof(scfContext))]
    [Migration("20221218141032_scfmig3")]
    partial class scfmig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BitirmeProjesiErp.Models.CariKart", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aktif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unvan")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.ToTable("CariKarts");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.CariKartAdresler", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_key_scf_carikart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adres1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adres2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adresadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carikartunvani")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.ToTable("CariKartAdreslers");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.CariKartYetkili", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_key_scf_carikart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_sis_rehber_karti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adsoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carikartkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ceptelno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gorev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istelno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.ToTable("CariKartYetkilis");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Doviz", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aktif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uzunadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.ToTable("Dovizs");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.OdemePlani", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aktif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kodu")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teklif_key")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("_key");

                    b.HasIndex("Teklif_key");

                    b.ToTable("OdemePlanis");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Rpr_dinamik_raporparametreleri_getir", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("isim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.ToTable("rpr_dinamik_raporparametreleri_getir");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.SatisElemanlari", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Teklif_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_key_scf_carikart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ceptel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.HasIndex("Teklif_key");

                    b.ToTable("SatisElemanlaris");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.StokKart", b =>
                {
                    b.Property<string>("_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aktif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birimisimleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birimkeyleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stokkartkodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.ToTable("StokKarts");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Teklif", b =>
                {
                    b.Property<string>("_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_key_prj_proje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_rpr_dinamik_raporparametreleri_getirs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_satiselemanlari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_scf_carikart")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_key_scf_carikart_adresleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_scf_carikart_yetkili")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_scf_odeme_plani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_sis_doviz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_sis_doviz_raporlama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_sis_sube_source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aciklama1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aciklama3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aktarildi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bagkur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bagkurdvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bagkuryuzde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("belgeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("borsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("borsadvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diafisno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diakey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dinamik10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dinamik7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dinamik8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dovizkuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dovizturu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ekalan1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ekalan2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ekalan3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ekalan4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ekalan5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ekalan6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fisno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("odemeplaniaciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("odemeplanikodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("onay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("raporlamadovizkuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rpr_dinamik_raporparametreleri_getirs_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("saat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sevkadresi1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sevkadresi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sevkadresi3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teslimattarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamaradvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamdvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamindirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamindirimdvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamkdv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamkdvdvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamkdvtevkifati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamkdvtevkifatidvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplammasraf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplammasrafdvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toplamovdvz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.HasIndex("_key_scf_carikart");

                    b.HasIndex("rpr_dinamik_raporparametreleri_getirs_key");

                    b.ToTable("Teklifs");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.TeklifKalemi", b =>
                {
                    b.Property<string>("_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_key_kalemturu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_key_prj_proje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_scf_fiyatkart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_scf_odeme_plani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_scf_satiselemani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_scf_teklif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_sis_doviz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_key_sis_sube_source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birimadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birimfiyati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dovizadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dovizkuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("miktar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teklif_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tutari")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_key");

                    b.HasIndex("_key_kalemturu");

                    b.HasIndex("teklif_key");

                    b.ToTable("TeklifKalemis");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.TeklifViewModel", b =>
                {
                    b.Property<string>("CariKart_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("carikey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teklif_key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("CariKart_key");

                    b.HasIndex("teklif_key");

                    b.ToTable("TeklifViewModel");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.OdemePlani", b =>
                {
                    b.HasOne("BitirmeProjesiErp.Models.Teklif", null)
                        .WithMany("OdemePlanis")
                        .HasForeignKey("Teklif_key");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.SatisElemanlari", b =>
                {
                    b.HasOne("BitirmeProjesiErp.Models.Teklif", null)
                        .WithMany("SatisElemanlaris")
                        .HasForeignKey("Teklif_key");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Teklif", b =>
                {
                    b.HasOne("BitirmeProjesiErp.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("_key_scf_carikart");

                    b.HasOne("BitirmeProjesiErp.Models.Rpr_dinamik_raporparametreleri_getir", "rpr_dinamik_raporparametreleri_getirs")
                        .WithMany()
                        .HasForeignKey("rpr_dinamik_raporparametreleri_getirs_key");

                    b.Navigation("CariKart");

                    b.Navigation("rpr_dinamik_raporparametreleri_getirs");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.TeklifKalemi", b =>
                {
                    b.HasOne("BitirmeProjesiErp.Models.StokKart", "StokKart")
                        .WithMany()
                        .HasForeignKey("_key_kalemturu");

                    b.HasOne("BitirmeProjesiErp.Models.Teklif", "teklif")
                        .WithMany("TeklifKalemis")
                        .HasForeignKey("teklif_key");

                    b.Navigation("StokKart");

                    b.Navigation("teklif");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.TeklifViewModel", b =>
                {
                    b.HasOne("BitirmeProjesiErp.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKart_key");

                    b.HasOne("BitirmeProjesiErp.Models.Teklif", "teklif")
                        .WithMany()
                        .HasForeignKey("teklif_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CariKart");

                    b.Navigation("teklif");
                });

            modelBuilder.Entity("BitirmeProjesiErp.Models.Teklif", b =>
                {
                    b.Navigation("OdemePlanis");

                    b.Navigation("SatisElemanlaris");

                    b.Navigation("TeklifKalemis");
                });
#pragma warning restore 612, 618
        }
    }
}
